spring:
  mail:
    host: smtp.fastmail.com
    port: 587
    username: ${FASTMAIL_USERNAME}
    password: ${FASTMAIL_PASSWORD}
    from: ${FASTMAIL_USERNAME}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  datasource:
    url: jdbc:h2:file:./data/reminderdb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update



