# Use your fastmail username/email
export FASTMAIL_USERNAME=payne@mattpayne.org
# Use https://app.fastmail.com/settings/security/apps to create a fastmail app
export FASTMAIL_PASSWORD=PW generated by fastmail for this app
